spring:
  thymeleaf:
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    encoding: UTF-8
    suffix: .html
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xjh.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


user:
  address:
    max-count: 10

logging:
  file:
    name: spring-logback.xml