spring:
  thymeleaf:
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    encoding: UTF-8
    suffix: .html
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xjh.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl